### PR TITLE
Stateless Latest and Session

### PR DESCRIPTION
**Pull request by emigiusto**
There are two new tables called:
- sessions
- latest

I didn't confirm 100% that the session is not retrieved from the app's memory (It shouldn't)

### CODE REVIEW

**Comment by nikogio** [comment]
to test:

update latest
sending a latest as a string
sending it as 0 
sending it as a -1 
latest work (send as a query parameter)

**Comment by nikogio** [comment]
EASILY RECOGNISABLE

**Comment by nikogio** [comment]
Sending latest as a string updates latest as null value 
Screenshot 2023-05-09 at 19 49 23

updating latest to 0 or -1 updates the value

**Comment by emigiusto** [comment]
Very good catch Nico! It is a bug indeed, and we never noticed it, probably because the simulator always sent the expected value. 

However, you are testing the real app and not the current branch to be merged. Do you know what happens when we sent a null value to the dba (though the implementation of this branch)?

**Comment by nikogio** [comment]
Testing on the app ran locally from this branch, when updating latest with a string value, app catches it with a NaN error, then crashes 

Screenshot 2023-05-11 at 14 26 54

**Comment by nikogio** [comment]
sessions:

loggin in ,closing browser and re-opening, does not keep the user logged in (tested both in local on this branch and on live minitwit)

**Comment by nikogio** [comment]
Screenshot 2023-05-11 at 15 28 57
updating latest works correctly but gives type error in the body. To verify,  sending GET request http://localhost:3000/latest returns the int I updated previously

**Comment by emigiusto** [comment]
This was fixed. There was a validation missing when we didn't receive a password.

In your payload you were not sending a password, as the body param should have the key "pwd"

**Pull request merged**
